- name: Provisionning webservers group
  hosts: central-server
  become: yes
  tasks:


  - pip:
      name: pymysql  

#  - name: Centreon Web Installation removing root password
#    mysql_user: name=root
#                password=''
#                login_user=mysql
#                state=present
#

#  - name: update mysql root password for all root accounts "{{ dbpass }}"
#    mysql_user: name=root password="{{ dbpass }}" priv="{{ dbname }}.*:ALL,GRANT"
#    with_items:
#      - localhost
#      - 127.0.0.1

  - name: Centreon UI editing www/index.html
    replace:
      path: /lib/systemd/system/mariadb.service
      regexp: 'LimitNOFILE=16364'
      replace: 'LimitNOFILE=32000'

  - name:
    systemd:
      name: "{{ item }}"
      state: reloaded
    with_items:
      - 'apache2'
      - 'php7.1-fpm'
