- name: Provisionning webservers group
  hosts: central-server
  become: yes
  tasks:


  - name: Centreon UI creating file .htaccess
    copy:
      content: | 
        RewriteRule ^index\.html$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /index.html [L]
        ErrorDocument 404 /centreon/index.html
      dest: "/usr/share/centreon/www/.htaccess"

  - name: changing owner to www directory
    file:
      path: /usr/share/centreon/www/
      owner: www-data
#      group: foo
